config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top' #TOPページ
  namespace :store do
    resources :stores, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      get '/stores/login', to: 'stores#sessions#new'
      post '/stores/login', to: 'stores#sessions#create'
      delete '/stores/logout', to: 'stores#sessions#destroy'
      resources :categories, only: [:index, :edit, :create, :update, :destroy]
      resources :genres, only: [:index, :edit, :create, :update, :destroy]
      resources :drinks, only: [:new, :create, :index, :show, :edit, :update, :destroy]
      end
    resources :employees, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :staffs, only: [:new, :create, :index, :show, :edit, :update, :destroy]

end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :genres , dependent: :destroy
  has_many :drinks , dependent: :destroy
  belongs_to :store
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :store
  belongs_to :category
  belongs_to :genre
end

app/models/employee.rb
class Employee < ApplicationRecord

end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :store
  belongs_to :category
  has_many :drinks , dependent: :destroy
end

app/models/staff.rb
class Staff < ApplicationRecord

end

app/models/store.rb
class Store < ApplicationRecord
  has_secure_password
   has_many :genres , dependent: :destroy
   has_many :categories , dependent: :destroy
   has_many :drinks , dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_store
  # before_action :login_required

  private

  def current_store
    @current_store ||= Store.find_by(id: session[:store_id]) if session[:store_id]
  end
  
  # def login_required
  #   redirect_to login_path unless current_store
  # #ログインしていない限り、ログイン画面にレダイレクト
  # end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # def top
  #   @store = Store.find(params[:store_id])
  # end
end

app/controllers/store/categories_controller.rb
class Store::CategoriesController < ApplicationController

  def index
    @category = Category.new
    @store = Store.find(params[:store_id])
    @categories = Category.where(store_id: @store)
  end

  def create
    @category = Category.new(category_params)
    @store = Store.find(params[:store_id])
    @category.store_id = @store.id
    if @category.save
      redirect_to store_store_categories_path(@store)
    else
      @store = Store.find(params[:store_id])
      @categories = Category.where(store_id: @store.id)
      render 'index'
    end
  end

  def edit
    @category = Category.find(params[:id])
    
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to store_store_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @store = Store.find(params[:store_id])
    @category.destroy
    redirect_to store_store_categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name, :store_id)
  end

end

app/controllers/store/drinks_controller.rb
class Store::DrinksController < ApplicationController

 def new
    @drink = Drink.new
    @store = Store.find(params[:store_id])
 end

 def create
    @drink = Drink.new(drink_params)
    @store = Store.find(params[:store_id])
    @drink.store_id = @store.id
    if @drink.save
      redirect_to store_store_drink_path(@store, @drink.id)
    else
      render 'new'
    end
 end

 def index
    @store = Store.find(params[:store_id])
    @categories = Category.where(store_id: @store)
    @genres = Genre.where(category_id: @categories)
    @drinks = Drink.where(genre_id: @genres)
 end

 def show
   @store = Store.find(params[:store_id])
   @drink = Drink.find(params[:id])
 end

 def edit
   @store = Store.find(params[:store_id])
   @drink = Drink.find(params[:id])
 end

 def update
   @store = Store.find(params[:store_id])
   @drink = Drink.find(params[:id])
    if @drink.update(drink_params)
      redirect_to store_store_drinks_path(@store, @drink.id)
    else
      render 'edit'
    end
 end

 def destory
 end

 private
 def drink_params
    params.require(:drink).permit(:name, :store_id, :category_id, :genre_id, :selling_price, :cost, :cost_rate, :material, :make)
 end

end

app/controllers/store/employees_controller.rb
class Store::EmployeesController < ApplicationController
end

app/controllers/store/genres_controller.rb
class Store::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @store = Store.find(params[:store_id])
    @genres = Genre.where(store_id: @store)
    
  end

  def create
    @genre = Genre.new(genre_params)
    @store = Store.find(params[:store_id])
    @genre.store_id = @store.id
    if @genre.save
      redirect_to store_store_genres_path(@store)
    else
      @store = Store.find(params[:store_id])
      @genres = Genre.where(store_id: @store.id)
      render 'index'
    end
  end

  def edit
    @store = Store.find(params[:store_id])
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to store_store_genres_path
    else
      render 'edit'
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @store = Store.find(params[:store_id])
    @genre.destroy
    redirect_to store_store_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :store_id, :category_id)
  end

end

app/controllers/store/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    store = Store.find_by(email: session_params[:email])
    #送られたメースアドレスでユーザーを検索

    if store&.authenticate(session_params[:password])
    session[:store_id]=store.id
    redirect_to root_path, notice: 'ログインしました'
    else
      render :new
    end
  end
  
  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end


end

app/controllers/store/staffs_controller.rb
class Store::StaffsController < ApplicationController
end

app/controllers/store/stores_controller.rb
class Store::StoresController < ApplicationController

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to store_store_path(@store.id)
    else
      render :new
    end
  end

  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    if @store.update(store_params)
      redirect_to store_store_path
    else
      render 'edit'
    end
  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy
    redirect_to store_stores_path(@store.id)
  end

  private
    def store_params
      params.require(:store).permit(:name, :email, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/store/categories_helper.rb
module Store::CategoriesHelper
end

app/helpers/store/drinks_helper.rb
module Store::DrinksHelper
end

app/helpers/store/employees_helper.rb
module Store::EmployeesHelper
end

app/helpers/store/genres_helper.rb
module Store::GenresHelper
end

app/helpers/store/staffs_helper.rb
module Store::StaffsHelper
end

app/helpers/store/stores_helper.rb
module Store::StoresHelper
end

app/views/store/categories/edit.html.erb
<div class="title">
  <p>カテゴリー更新</p>
</div>
<div class='category-edit'>
  <%= form_with model: @category, url: store_store_category_path, local: true do |f| %>
  <%= f.label 'カテゴリー名', class: 'col-sm-8' %><br>
  <%= f.text_field :name, class: 'col-sm-8', placeholder: "例)仕込みorカルトorFD" %>
  <br><%= f.submit 'カテゴリー名更新', class:'btn btn-primary' %></br>
  <% end %>
</div>

app/views/store/categories/index.html.erb
<div class="title">
  <p>カテゴリー作成&一覧</p>
</div>
<div class="link-category">
  <%= link_to '店舗', store_store_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'カテゴリー作成&一覧', store_store_categories_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ジャンル作成&一覧', store_store_genres_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ドリンク作成', new_store_store_drink_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ドリンク一覧', store_store_drinks_path(@store), class: 'btn setting_btn btn-success' %>
</div>
<div class="category-imformation">
  <div class="category-new">
    <h2>カテゴリー作成</h2>
    <%= form_with model: @category, url: store_store_categories_path(@store, @category.id), local: true do |f| %>
    <div>
      <%= f.label 'カテゴリー名', class: 'col-sm-8' %><br>
      <%= f.text_field :name, class: 'col-sm-8', placeholder: "例)仕込みorカルトorFD" %>
    </div>
    <div class='text-center'>
      <%= f.submit '新規登録', class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
  <div class="category-index">
  <h2>カテゴリー一覧</h2>
  <table class="table">
    <thead>
      <tr>
        <th>カテゴリー名</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to '編集', edit_store_store_category_path(@store.id, category.id), class: 'btn setting_btn btn-success' %></td>
        <td><%= link_to '削除', store_store_category_path(@store.id, category.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn setting_btn btn-danger "%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/store/drinks/edit.html.erb
<div class="title">
  <h1>ドリンク編集</h1>
</div>

<div class="drink-edit">
  <%= form_with model: @drink, url: store_store_drink_path, local: true do |f| %>
  <div>
    <%= f.label 'ドリンク名', class: 'col-sm-8' %>
    <%= f.text_field :name, class: 'col-sm-8', placeholder: "ドリンク名" %>
  </div>
  <div class='form-group'>
    <%= f.label 'ジャンル名', class: 'col-sm-3' %>
    <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: '選択してください'}, class: 'col-sm-8' %>
  </div>
  <div class='form-group'>
    <%= f.label 'ジャンル名', class: 'col-sm-3' %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: '選択してください'}, class: 'col-sm-8' %>
  </div>
  <div>
    <%= f.label '販売価格名', class: 'col-sm-8' %>
    <%= f.text_field :selling_price, class: 'col-sm-8', placeholder: "例)500円" %>
  </div>
  <div>
    <%= f.label '原価', class: 'col-sm-8' %>
    <%= f.text_field :cost, class: 'col-sm-8', placeholder: "例)50円" %>
  </div>
  <div>
    <%= f.label '原価率', class: 'col-sm-8' %>
    <%= f.text_field :cost_rate, class: 'col-sm-8', placeholder: "例)10%" %>
  </div>
  <div>
    <%= f.label '商材', class: 'col-sm-8' %>
    <%= f.text_field :material, size: 40,  class: 'col-sm-8', placeholder: "" %>
  </div>
  <div>
    <%= f.label '作り方', class: 'col-sm-8' %>
    <%= f.text_field :make, size: 40, class: 'col-sm-8', placeholder: "" %>
  </div>
  <div class='text-center'>
    <%= f.submit 'ドリンク情報', class: 'btn btn-success' %>
  </div>
  <% end %>
  <%= link_to store_store_drink_path(@store, @drink.id) do %>
    <h4>ドリンク詳細に戻る</h4>
  <% end %>

app/views/store/drinks/index.html.erb
<div class="title">
  <p>ドリンク一覧</p>
</div>
<div class="link-drink">
  <%= link_to '店舗', store_store_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'カテゴリー作成&一覧', store_store_categories_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ジャンル作成&一覧', store_store_genres_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ドリンク作成', new_store_store_drink_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ドリンク一覧', store_store_drinks_path(@store), class: 'btn setting_btn btn-success' %>
</div>
<div class="drink-index">
  <% @categories.each do |category| %>
  <div class="drink-category-index">
    <p><%= category.name %></p>
  </div>
  <div>
    <% @genres.each do |genre| %>
    <div class="drink-genre-index">
      <p><%= genre.name %></p>
    </div>
  </div>
    <div class="drink-index-table">
      <div class="drink-box">
        <% @drinks.each do |drink| %>
        <div>ドリンク名</div>
        <div>
          <%= link_to store_store_drink_path(@store, drink.id) do %>
          <%= drink.name%>
          <% end %>
          <div class="drink-category">
            <div>カテゴリー名</div>
            <div><%= drink.category.name%></div>
          </div>
          <div class="drink-genre">
            <div>ジャンル名</div>
            <div><%= drink.genre.name%></div>
          </div>
          <div class="drink-price">
            <div>販売価格</div>
            <div><%= drink.selling_price%>円</div>
          </div>
          <div class="drink-cost">
            <div>原価</div>
            <div><%= drink.cost%>円</div>
          </div>
          <div class="drink-cost-rate">
            <div>原価率</div>
            <div><%= drink.cost_rate %>％</div>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
    </div>
  <% end %>
  </div>
</div>

app/views/store/drinks/new.html.erb
<div class="title">
  <h1>ドリンク作成</h1>
</div>
<div class="link-drink">
  <%= link_to '店舗', store_store_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'カテゴリー作成&一覧', store_store_categories_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ジャンル作成&一覧', store_store_genres_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ドリンク一覧', store_store_drinks_path(@store), class: 'btn setting_btn btn-success' %>
</div>
<div class="drink-new">
  <h2>ドリンク作成</h2>
  <%= form_with model: @drink, url: store_store_drinks_path(@store), local: true do |f| %>
  <div>
    <%= f.label 'ドリンク名', class: '' %>
    <%= f.text_field :name, class: '', placeholder: "ドリンク名" %>
  </div>
  <div class='form-group'>
    <%= f.label 'カテゴリー名', class: '' %>
    <%= f.collection_select :category_id, Category.where(store_id: @store), :id, :name, { prompt: '選択してください'}, class: '' %>
  </div>
  <div class='form-group'>
    <%= f.label 'ジャンル名', class: '' %>
    <%= f.collection_select :genre_id, Genre.where(store_id: @store), :id, :name, { prompt: '選択してください'}, class: '' %>
  </div>
  <div>
    <%= f.label '販売価格', class: '' %>
    <%= f.text_field :selling_price, class: '', placeholder: "例)500円" %>
  </div>
  <div>
    <%= f.label '原価', class: '' %>
    <%= f.text_field :cost, class: '', placeholder: "例)50円" %>
  </div>
  <div>
    <%= f.label '原価率', class: '' %>
    <%= f.text_field :cost_rate, class: '', placeholder: "例)10%" %>
  </div>
  <div>
    <%= f.label '商材', class: '' %>
    <%= f.text_field :material, size: 40, class: 'text-material', placeholder: "" %>
  </div>
  <div>
    <%= f.label '作り方', class: '' %>
    <%= f.text_field :make, size: 40, class: 'text-make', placeholder: "" %>
  </div>
  <div class='text-center'>
    <%= f.submit '新規登録', class: 'btn btn-success' %>
  </div>
  <% end %>

app/views/store/drinks/show.html.erb
<div class="title">
  <p>ドリンク詳細</p>
</div>
<div class="link-drink">
  <%= link_to '店舗', store_store_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'カテゴリー作成&一覧', store_store_categories_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ジャンル作成&一覧', store_store_genres_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ドリンク作成', new_store_store_drink_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ドリンク一覧', store_store_drinks_path(@store), class: 'btn setting_btn btn-success' %>
</div>
<div class="link-drink">
  <%= link_to 'ドリンク情報編集', edit_store_store_drink_path(@store, @drink.id), class: 'btn setting_btn btn-success' %>
</div>

<div class="drink-information">
  <div>
    <span>ドリンク名  </span><%= @drink.name%>
  </div>
  <div>
    <span>カテゴリー名  </span><%= @drink.category.name%>
  </div>
  <div>
    <span>ジャンル名  </span><%= @drink.genre.name%>
  </div>
  <div>
    <span>販売価格  </span><%= @drink.selling_price%>
  </div>
  <div>
    <span>原価  </span><%= @drink.cost%>
  </div>
  <div>
    <span>原価率  </span><%= @drink.cost_rate%>
  </div>
</div>

app/views/store/employees/index.html.erb
<h1>カテゴリー作成&一覧</h1>
<div>
  <h4>カテゴリー作成</h4>
  <div>
    
  </div>
</div>

app/views/store/genres/edit.html.erb
<div class="title">
  <p>ジャンル更新</p>
</div>
<div class='genre-edit'>
  <%= form_with model: @genre, url: store_store_genre_path, local: true do |f| %>
  <%= f.label 'ジャンル名', class: '' %>
  <%= f.text_field :name, class: '', placeholder: "例" %>
  <%= f.label 'カテゴリー', class: '' %>
    <%= f.collection_select :category_id, Category.where(store_id: @store.id), :id, :name, { prompt: '選択してください'}, class: 'col-sm-8' %>
  <br><%= f.submit 'ジャンル名更新', class:'btn btn-primary' %></br>
  <% end %>
</div>

app/views/store/genres/index.html.erb
<div class="title">
  <p>ジャンル作成&一覧</p>
</div>
<div class="link-genre">
  <%= link_to '店舗', store_store_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'カテゴリー作成&一覧', store_store_categories_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ジャンル作成&一覧', store_store_genres_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ドリンク作成', new_store_store_drink_path(@store), class: 'btn setting_btn btn-success' %>
  <%= link_to 'ドリンク一覧', store_store_drinks_path(@store), class: 'btn setting_btn btn-success' %>
</div>
<div class="genre-information">
  <div class="genre-new">
    <h2>ジャンル作成</h2>
    <%= form_with model: @genre, url: store_store_genres_path(@store), local: true do |f| %>
    <div>
      <%= f.label 'ジャンル名', class: 'col-sm-8' %>
      <%= f.text_field :name, class: 'col-sm-8', placeholder: "例)仕込みorカルトorFD" %>
    </div>
    <div class='form-group'>
      <%= f.label 'カテゴリー', class: 'col-sm-3' %>
      <%= f.collection_select :category_id, Category.where(store_id: @store), :id, :name, { prompt: '選択してください'}, class: 'col-sm-8' %>
    </div>
    <div class='text-center'>
      <%= f.submit '新規登録', class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
  <div class="genre-index">
    <h2>ジャンル一覧</h2>
    <table class="table">
      <thead>
        <tr>
          <th>ジャンル名</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= link_to '編集', edit_store_store_genre_path(@store.id, genre.id), class: 'btn setting_btn btn-success' %></td>
          <td><%= link_to '削除', store_store_genre_path(@store.id, genre.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn setting_btn btn-danger "%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/store/stores/edit.html.erb
<div class="title">
  <p>店舗情報編集</p>
</div>
<div class="edit-information">
  <%= link_to '店舗情報', store_store_path(@store.id), class: 'btn setting_btn btn-success' %>
  <%= form_with model: @store, url: store_store_path(), local: true do |f| %>
  <div>
    <%= f.label '店舗名', class: 'col-sm-8' %>
    <%= f.text_field :name, class: 'col-sm-8', placeholder: "店舗名" %>
  </div>
  <div>
    <%= f.label 'メールアドレス', class: 'col-sm-8' %>
    <%= f.text_field :email, class: 'col-sm-8', placeholder: "メールアドレス" %>
  </div>
  <div>
    <%= f.label 'パスワード', class: 'col-sm-8' %>
    <%= f.text_field :password_digest, class: 'col-sm-8', placeholder: "パスワード" %>
  </div>
  <div class='text-center'>
    <%= f.submit '店舗情報変更', class: 'btn btn-success' %>
  </div>
  <% end %>
</div>

app/views/store/stores/index.html.erb
<div class="title">
  <p>店舗一覧</p>
</div>
<div class="index-title">
  <div class="table-form">
    <div class="name-title">店舗名</div>
    <div class="category-title">カテゴリー数</div>
    <div class="genre-title">ジャンル数</div>
    <div class="drinks-title">商品数</div>
  </div>
  <% @stores.each do |store| %>
    <div class="drink-information-index">
      <div class="name">
        <%= link_to store_store_path(store.id) do %>
        <%= store.name%>
        <% end %>
      </div>
      <div class="category"><%= store.category_ids.count %></div>
      <div class="genre"><%= store.genre_ids.count %></div>
      <div class="drinks">
        <%= link_to store_store_drinks_path(store.id) do %>
        <%= store.drink_ids.count %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/store/stores/new.html.erb
<div class="title">
  <p>店舗登録</p>
</div>
<div class="store-new-form">
  <%= form_with model: @store, url: store_stores_path, local: true do |f| %>
  <div>
    <%= f.label '店舗名', class: 'col-sm-8' %>
    <%= f.text_field :name, class: 'col-sm-8', placeholder: "店舗名" %>
  </div>
  <div>
    <%= f.label 'メールアドレス', class: 'col-sm-8' %>
    <%= f.text_field :email, class: 'col-sm-8', placeholder: "メールアドレス" %>
  </div>
  <div>
    <%= f.label 'パスワード', class: 'col-sm-8' %>
    <%= f.text_field :password_digest, class: 'col-sm-8', placeholder: "パスワード" %>
  </div>
  <div class='text-center'>
    <%= f.submit '新規登録', class: 'btn btn-success' %>
  </div>
  <% end %>
</div>

app/views/store/stores/show.html.erb
<div class="title">
  <p><%= @store.name%></p>
</div>
<div class="link-store">
    <%= link_to '編集', edit_store_store_path(@store.id), class: 'btn setting_btn btn-success' %>
    <%= link_to '削除', store_store_path(@store.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn setting_btn btn-danger "%>
    <%= link_to '店舗一覧', store_stores_path, class: 'btn setting_btn btn-success' %>
    <%= link_to 'カテゴリー作成&一覧', store_store_categories_path(@store), class: 'btn setting_btn btn-success' %>
    <%= link_to 'ジャンル作成&一覧', store_store_genres_path(@store), class: 'btn setting_btn btn-success' %>
    <%= link_to 'ドリンク作成', new_store_store_drink_path(@store), class: 'btn setting_btn btn-success' %>
    <%= link_to 'ドリンク一覧', store_store_drinks_path(@store), class: 'btn setting_btn btn-success' %>
</div>
<div class="show-information">
  <div>
    <span>カテゴリー数  </span><%= @store.category_ids.count %>
  </div>
  <div>
    <span>ジャンル数  </span><%= @store.genre_ids.count %>
  </div>
  <div>
    <span>ドリンク数  </span><%= @store.drink_ids.count %>
  </div>
</div>